#pragma once

#define SYS_BOARD_VERSION 2
#define SYS_CLOCK_FROM_ETH 0	// use clock generated by enc to drive uC (12,5MHz)

#define SYS_ID 	"K2T-W"
#define SYS_VER "v2.0"

//#define SYS_ENABLE_AS110x
#define SYS_AS110X_DISPLAYS 5

#define CONFIG_EEPROM_NET 	0x0000
#define CONFIG_EEPROM_BOOT 	0x0040